name: 'Build-Mac'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      mode: '["build"]'
      alphas: '["default"]'
      extra: '["colemakdh"]'
      nav: '["vi"]'
      clipboard: '["mac"]'
      layers: '["default"]'
      mapping: '["default"]'
      kmonad_os: '["mac"]'
      rules: '["default"]'
      custom_config: '["default"]'
